"""add annotated_image_url

Revision ID: 3c65b2676914
Revises: 8d4483b1c59f
Create Date: 2026-03-30 20:56:22.582849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c65b2676914'
down_revision: Union[str, None] = '8d4483b1c59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('annotated_image_url', sa.String(length=512), nullable=True))
    op.alter_column('analysis_tasks', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis_tasks', 'step_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_tasks', 'step_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('analysis_tasks', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('analysis_tasks', 'annotated_image_url')
    # ### end Alembic commands ###