"""add progress fields

Revision ID: 8d4483b1c59f
Revises: 
Create Date: 2026-03-23 15:26:55.237369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8d4483b1c59f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('current_step', sa.String(length=50), nullable=True))
    op.add_column('analysis_tasks', sa.Column('progress_message', sa.Text(), nullable=True))
    op.add_column('analysis_tasks', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('analysis_tasks', sa.Column('step_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'step_details')
    op.drop_column('analysis_tasks', 'progress_percent')
    op.drop_column('analysis_tasks', 'progress_message')
    op.drop_column('analysis_tasks', 'current_step')
    # ### end Alembic commands ###